sudo: required
dist: xenial

language: cpp

env:
    matrix:
        - QT_VERSION=56 QT_PATCH=3
        - QT_VERSION=59 QT_PATCH=3

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test

before_install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt${QT_VERSION}${QT_PATCH}-xenial
    - sudo apt-get update

install:
    - sudo apt-get install -y -qq qt${QT_VERSION}base

before_script:
    - source /opt/qt$QT_VERSION/bin/qt${QT_VERSION}-env.sh;
    - g++ --version

script:
    - cmake .
    - make -j2
    - sudo cp src/moc `which moc`
    - mkdir test_build && cd test_build
    - qmake
    - make check -j2
